### ISSUE TITLE
gopages command doesn't work on windows properly, wipes out project

### ISSUE THREAD

**Issue by sacOO7** [JohnStarich/go#27] opened 2022-11-18 18:36 UTC
- go version go1.19.3 windows/amd64
- When `gopages` is run, it generates doc but it's recursive and it doesn't close after running.
- Links pointing to `embedded go source code` are broken.
- There also seems to be some serious issue about how file paths are handled in windows, it mistakenly deleted my whole project after running the code

```
PS C:\Users\dummy\GolandProjects\dummy-go> gopages --out C:\Users\dummy\GolandProjects
Generating godoc static pages for module... github.com/tt/dummy-go
pipe: Failed to clean output directory: remove C:\Users\dummy\GolandProjects\dummy-go: The process cannot access the file because it is being used by another process.
```

This wiped out my entire project.

**Comment by JohnStarich** [comment] 2022-11-28 22:59
@sacOO7 Thanks for opening. Ouch! That last one sounds like a big pain 🤕 

> * When `gopages` is run, it generates doc but it's recursive and it doesn't close after running.

When you say it is recursive what do you mean? By not closing, do you mean the program hangs? I'll see if I can reproduce, maybe even add Windows to the CI test suite too.

> * Links pointing to `embedded go source code` are broken.

Do you have similar symptoms to https://github.com/JohnStarich/go/issues/25?

> * There also seems to be some serious issue about how file paths are handled in windows, it mistakenly deleted my whole project after running the code

It looks like the flags were set such that the output directory was not a temporary one, which the tool didn't expect. Maybe we can do some extra detection to see if the output dir is a gopages result before attempting removal. That way it could initially refuse if it would wipe out something important. We might need a new `--force` flag as well.

**Comment by JohnStarich** [comment] 2022-11-29 09:17
Pretty sure I've just found the infinite recursion bug you mentioned in #31. 31 has the fix, and hopefully can merge soon.

It took my entire day to find and fix all of the Windows-specific test failures. 🙃 Will resume soon.

**Comment by JohnStarich** [comment] 2022-12-01 06:35
@sacOO7 The fix for hanging on Windows has been merged. Also, the source code links might be fixed for you now. Please let me know which HTTP server you're using if they're still busted.

I haven't touched the `-out` flag behavior just yet, that's next.

**Comment by sacOO7** [comment] 2022-12-01 06:37
Yeah, I will try to test it on `sandbox` environment, so it's safe. Thanks for resolving the issue 👍

**Comment by sacOO7** [comment] 2022-12-01 19:40
So, I tested the latest `gopages` command on the windows, my observations

1. It's able to generate `dist` directory with necessary files, it doesn't get blocked, and no recursive bugs/directories
2. I can navigate to different source links ( not broken anymore )

**Important** -  I didn't test it with `-out` flag yet, since it's yet to be updated. I think that the operation is dangerous in the first place, we should try to avoid it. You can post here once it's fixed, I will test it out.

### About static HTTP server 
I am using python local `http.server`, you can try this command 
```python
py -m http.server 8000
```
I think you should include this command in the `gopages published doc => https://johnstarich.com/go/gopages/pkg/github.com/johnstarich/go/gopages/

**Comment by JohnStarich** [comment] 2022-12-02 00:15
Great to hear on 1 and 2 🎉 

Excellent, thanks. I'll keep that kind of server in mind if we hit further issues.

Interesting idea. Another option might be to include an HTTP file server inside the `gopages` command, since they're relatively easy to write in Go.

**Closed** 2022-12-02 01:31 UTC

**Comment by JohnStarich** [comment] 2022-12-02 01:32
@sacOO7 Should be all set with the latest release of gopages `v0.1.16`. Can you give that a shot? (Also in a sandbox at first, to be extra safe!)

**Comment by sacOO7** [comment] 2022-12-02 04:44
Sure, I would give it a try

**Comment by sacOO7** [comment] 2022-12-02 04:45
I didn't understand => How can it delete the directory if it doesn't exist?

**Comment by JohnStarich** [comment] 2022-12-02 06:04
Ha, good point. Without context, it doesn't really make sense! I guess I meant to say it will proceed with the equivalent of `os.RemoveAll()` when any of those conditions are true. 😄

**Comment by sacOO7** [comment] 2022-12-02 19:02
Okay sure 👍
